### ISSUE TITLE
Write tests for existing DAO's

### ISSUE THREAD

**Issue by kuzux** [bounswe/bounswe2016group3#103]
If we can get to automate those tests as well, we can pretty much ensure that the entire backend works via automated tests.

**Comment by kuzux** [comment]
https://gist.github.com/yunspace/9a50e11dbd8661271220
this might be a resource to test dao s

**Comment by SanD94** [comment]
http://stackoverflow.com/questions/28388204/how-to-test-dao-methods-using-mockito
might be another resource

**Comment by kuzux** [comment]
Found a way to write tests for the DAOs. They use mappers as well when returning Data.
