### ISSUE TITLE
Which one do you think would be better?

### ISSUE THREAD

**Issue by NoorAhmd** [bounswe/bounswe2016group3#18]
@sinemdalkilic @kuzdogan 
![sequence chart - new page](https://cloud.githubusercontent.com/assets/17162219/14250003/2faca562-fa85-11e5-8792-93397cb666fd.jpeg)
![sequence1](https://cloud.githubusercontent.com/assets/17162219/14250004/2fc77810-fa85-11e5-98a7-7bbc5b210d64.png)

**Comment by NoorAhmd** [comment]
alttaki eski,, bu kadar detaya giremeye gerek varmi?

**Comment by sinemdalkilic** [comment]
Advance search'te 'preferences'lere gore seçim de yapabiliyoruz, onu da ekleyelim. Bir de actionların fiil olması gerekiyor. getInput gibi. Son olarak da if/else için ayrıca bir structure vardı onu da kullanabiliriz :)

**Comment by NoorAhmd** [comment]
yani daha cok detay lazim? :)
