### ISSUE TITLE
Research about lifecycles

### ISSUE THREAD

**Issue by sinemdalkilic** [bounswe/bounswe2016group3#2]

**Comment by sinemdalkilic** [comment]
Guys check this out! https://techazzist.files.wordpress.com/2012/05/sdlc-big.jpg

**Comment by behiyeavci** [comment]
Detailed explanation of agile methodology. I found it very useful! http://agilemethodology.org/

**Comment by behiyeavci** [comment]
I found this link very useful about agile. http://www.allaboutagile.com/agile-development-cycle/
