### ISSUE TITLE
Get user's name and picture from specific comment

### ISSUE THREAD

**Issue by ekremozturk** [bounswe/bounswe2016group3#206]
I can get user object who wrote the comment using getUserById. I add users to a list and send it to CommentAdapter. When I go to comments from meal details page, there is no problem but when I go back and click comments again I get an IndexOutOfBoundsException at random index.

I think that exception is caused because I set adapter multiple times in the for loop while calling users via apiService. I couldn't find a way to add users to userList first and set adapter after for loop ends (userList returns empty outside Callback method). Is there a way I can implement this properly?

**Comment by behiyeavci** [comment]
done for ViewMealCommentsActivity

**Comment by behiyeavci** [comment]
caused by asynchronized structure of calls
