### ISSUE TITLE
Research about Communication

### ISSUE THREAD

**Issue by kuzdogan** [bounswe/bounswe2016group3#4]

**Comment by kuzdogan** [comment]
@ekremozturk

**Comment by kuzdogan** [comment]
A great amusing TED-Ed video on miscommunication 
https://www.youtube.com/watch?time_continue=262&v=gCfzeONu3Mo

**Comment by ekremozturk** [comment]
10 ways to have a better conversation(starts at 4:27) http://go.ted.com/CZdE and a follow-up [article](http://www.upliftevents.com.au/blog/communicate-effectively-colleagues/) about productive communication.
