### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by behiyeavci** [bounswe/bounswe2016group3#6]
Hey guys! Please put your suggestions for the project name here!

**Comment by behiyeavci** [comment]
Yer misin

**Comment by muharremyesilyurt** [comment]
Bugun Ne Yesem ?

**Comment by behiyeavci** [comment]
Geldim Gördüm Yedim

**Comment by behiyeavci** [comment]
veni vidi edi

**Comment by kuzdogan** [comment]
Eet

**Comment by NoorAhmd** [comment]
Kurtgibiaciktim

**Comment by NoorAhmd** [comment]
imam bayildi :)

**Comment by NoorAhmd** [comment]
Yummy

**Comment by kuzdogan** [comment]
NeYesem

**Comment by kuzdogan** [comment]
Ambrosia
Check out: https://en.wikipedia.org/wiki/Ambrosia

**Comment by SanD94** [comment]
Afiyet

**Comment by ekremozturk** [comment]
Eatalyze

**Comment by sinemdalkilic** [comment]
eat me

**Comment by kuzdogan** [comment]
Afiyeat

**Comment by kuzdogan** [comment]
Healtee

**Comment by behiyeavci** [comment]
check eat (:

**Comment by ekremozturk** [comment]
DontJustEatIt

https://www.youtube.com/watch?v=oRdxUFDoQe0 read it in this rhyme

**Comment by kuzux** [comment]
bu saate kadar hala karar veremediysek adini feriha koyalim diyorum.
